# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Uživatelská dokumentace
site_url: https://docs.aputime.com/
site_author: ApuTime
site_description:

# Repository
repo_name: aputime/docs
repo_url: https://github.com/aputime/docs

# Copyright
copyright: Copyright &copy; 2016 - 2022 APUTime

# Configuration
theme:
  name: null
  custom_dir: material
  font: false
  features:
    - header.autohide
    - navigation.tabs

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: cs
  palette:
    scheme: default
  font:
    text: Manrope
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - exclude-search:
      exclude:
        - typography.md
        - cs/dokumentace/muj-profil.md
        - en/*
  #- monorepo
  - macros
  - markdownextradata
  - minify:
      minify_html: true # TODO change to TRUE

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
#- Home: index.md
- Dokumentace:
    - Návody: ./cs/dokumentace/navody.md
    - Notifikace a upozornění: ./cs/dokumentace/notifikace-a-upozorneni.md
    - Záložky: ./cs/dokumentace/zalozky.md
    - Podpora: ./cs/dokumentace/podpora.md
    - Workspace: ./cs/dokumentace/workspace.md
    - Jazyk: ./cs/dokumentace/jazyk.md
    - Nápověda: ./cs/dokumentace/napoveda.md
    - Provizní program: ./cs/dokumentace/provizni-program.md
    - Nastavení: ./cs/dokumentace/nastaveni.md
    - Předplatné: ./cs/dokumentace/predplatne.md
    - Podmínky zpracování osobních údajů: ./cs/dokumentace/podminky-zpracovani-osobnich-udaju.md
    - Můj plán: ./cs/dokumentace/muj-plan.md
    - Časová osa Gantt.AI™: ./cs/dokumentace/casova-osa-gantt-ai.md
    - Projekty: ./cs/dokumentace/projekty.md
    - ProjectFormation™: ./cs/dokumentace/projectformation.md
    - Strávený čas: ./cs/dokumentace/straveny-cas.md
    - Štítky, kategorie a skupiny: ./cs/dokumentace/stitky-kategorie-a-skupiny.md
    - Lidé: ./cs/dokumentace/lide.md
    - Jak nainstalovat webovou aplikaci ApuTime na mobilní telefon: ./cs/dokumentace/jak-nainstalovat-aputime-na-mobilni-telefon.md
- Changelog:
  - ./cs/changelog.md
- Dostupnost aplikace:
  - ./dostupnost-aplikace.md

# Extra Files
extra_css:
  - ./assets/stylesheets/glightbox.min.css
  - ./assets/stylesheets/extra.css
extra_javascript:
  - ./assets/javascripts/glightbox.min.js
  - ./assets/javascripts/extra.js

# Google Analytics
# google_analytics: ['UA-?', 'docs.aputime.com']
google_analytics: null
